name: Update Progress Tracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write   # ✅ allow pushing changes

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run progress update script
        run: python update_progress.py

      - name: Commit & push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🔄 Update progress tracker" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # ✅ use GitHub token
